=== tests/cases/conformance/internalModules/DeclarationMerging/module.d.ts ===
declare module A {
>A : 类为 A

    export module Point {
>Point : 类为 Point

        export var Origin: {
>Origin : { x: 数字; y: 数字; }

            x: number;
>x : 数字
>类型别名 :=> 数字

            y: number;
>y : 数字
>类型别名 :=> 数字
        }
    }
}

=== tests/cases/conformance/internalModules/DeclarationMerging/classPoint.ts ===
module A {
>A : 类为 A

    export class Point {
>Point : Point

        constructor(public x: number, public y: number) { }
>x : 数字
>类型别名 :=> 数字
>y : 数字
>类型别名 :=> 数字
    }
}

=== tests/cases/conformance/internalModules/DeclarationMerging/test.ts ===
var p: { x: number; y: number; }
>p : { x: 数字; y: 数字; }
>x : 数字
>类型别名 :=> 数字
>y : 数字
>类型别名 :=> 数字

var p = A.Point.Origin;
>p : { x: 数字; y: 数字; }
>A.Point.Origin : { x: 数字; y: 数字; }
>A.Point : 类为 A.Point
>A : 类为 A
>Point : 类为 A.Point
>Origin : { x: 数字; y: 数字; }

var p = new A.Point(0, 0); // unexpected error here, bug 840000
>p : { x: 数字; y: 数字; }
>new A.Point(0, 0) : A.Point
>A.Point : 类为 A.Point
>A : 类为 A
>Point : 类为 A.Point
>0 : 0
>0 : 0

